import { Customer, CustomerTimelineEvent } from '@/types';
import { customerRepository } from '@/repositories/repository';

export class CustomerService {
  /**
   * Validate a customer instance for business rule compliance.
   * Throws an error with details if validation fails.
   */
  async validate(customer: Partial<Customer>, isUpdate: boolean = false): Promise<void> {
    const errors: string[] = [];

    // Required fields check
    if (!customer.name?.trim()) errors.push('Company identity name is required');
    if (!customer.email?.trim()) errors.push('Contact email is required');
    if (!customer.country?.trim()) errors.push('Country of origin/dispatch is required');
    // paymentTerms may be a string or JSON object from DB — normalize to string
    const paymentTermsStr = typeof customer.paymentTerms === 'string' 
      ? customer.paymentTerms 
      : (customer.paymentTerms ? JSON.stringify(customer.paymentTerms) : '');
    if (!paymentTermsStr.trim()) errors.push('Payment terms are required');
    if (!customer.segment) errors.push('Customer segment is required');
    if (!customer.preferredDischargePortId) errors.push('Preferred Port of Discharge is required');

    // Email format validation
    if (customer.email?.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(customer.email.trim())) {
        errors.push('Contact email format is invalid');
      }
    }

    // Website format validation (if provided)
    if (customer.website?.trim()) {
      const webRegex = /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([\/\w .-]*)*\/?$/;
      if (!webRegex.test(customer.website.trim())) {
        errors.push('Website URL format is invalid');
      }
    }

    // Unique Email and Tax ID check
    if (customer.email?.trim()) {
      const existing = await customerRepository.find(c => 
        c.email.toLowerCase() === customer.email!.trim().toLowerCase() && 
        c.entityStatus !== 'DELETED' &&
        (!isUpdate || c.id !== customer.id)
      );
      if (existing.length > 0) {
        errors.push(`Email '${customer.email}' is already registered to another client`);
      }
    }

    if (customer.taxId?.trim()) {
      const existing = await customerRepository.find(c => 
        (c.taxId || '').toLowerCase() === customer.taxId!.trim().toLowerCase() && 
        c.entityStatus !== 'DELETED' &&
        (!isUpdate || c.id !== customer.id)
      );
      if (existing.length > 0) {
        errors.push(`Tax ID '${customer.taxId}' is already registered to another client`);
      }
    }

    // Credit limit check
    if (customer.creditLimit !== undefined && customer.creditLimit < 0) {
      errors.push('Credit limit cannot be negative');
    }

    if (errors.length > 0) {
      throw new Error(errors.join(' | '));
    }
  }

  /**
   * Add a timeline event to a customer
   */
  logEvent(
    customer: Customer, 
    type: CustomerTimelineEvent['type'], 
    title: string, 
    description: string, 
    userId: string = 'USR-001'
  ): void {
    if (!customer.timeline) {
      customer.timeline = [];
    }
    
    const event: CustomerTimelineEvent = {
      id: `EV-${Math.random().toString(36).substr(2, 9)}`,
      date: new Date().toISOString(),
      type,
      title,
      description,
      userId
    };

    customer.timeline.unshift(event);
  }

  /**
   * Clones a customer node.
   */
  async duplicate(id: string): Promise<Customer> {
    const original = await customerRepository.getById(id);
    if (!original) throw new Error('Client matrix node not found');

    const duplicatedCustomer: Partial<Customer> = {
      ...original,
      id: undefined, // Generated by repo
      name: `${original.name} (Copy)`,
      taxId: original.taxId ? `${original.taxId}-COPY` : undefined,
      email: `copy.${original.email}`,
      timeline: [
        {
          id: `EV-${Math.random().toString(36).substr(2, 9)}`,
          date: new Date().toISOString(),
          type: 'CREATED',
          title: 'Client Profile Duplicated',
          description: `Duplicated from original client SKU ID: ${original.id}.`,
          userId: 'USR-001'
        }
      ],
      entityStatus: 'ACTIVE'
    };

    return customerRepository.create(duplicatedCustomer);
  }
}

export const customerService = new CustomerService();
