import { Forwarder, ForwarderTimelineEvent } from '@/types';
import { forwarderRepository } from '@/repositories/repository';

export class ForwarderService {
  /**
   * Validate a forwarder instance for business rules.
   */
  async validate(forwarder: Partial<Forwarder>, isUpdate: boolean = false): Promise<void> {
    const errors: string[] = [];

    // Required fields check
    if (!forwarder.name?.trim()) errors.push('Forwarder identity name is required');
    if (!forwarder.email?.trim()) errors.push('Contact email is required');
    if (!forwarder.country?.trim()) errors.push('Country of origin/dispatch is required');
    if (!forwarder.preferredPorts || forwarder.preferredPorts.length === 0) {
      errors.push('At least one preferred port of operation must be selected');
    }

    // Email validation
    if (forwarder.email?.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(forwarder.email.trim())) {
        errors.push('Contact email format is invalid');
      }
    }

    // Website validation
    if (forwarder.website?.trim()) {
      const webRegex = /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([\/\w .-]*)*\/?$/;
      if (!webRegex.test(forwarder.website.trim())) {
        errors.push('Website URL format is invalid');
      }
    }

    // Unique Email and Tax ID check
    if (forwarder.email?.trim()) {
      const existing = await forwarderRepository.find(f => 
        f.email.toLowerCase() === forwarder.email!.trim().toLowerCase() && 
        f.entityStatus !== 'DELETED' &&
        (!isUpdate || f.id !== forwarder.id)
      );
      if (existing.length > 0) {
        errors.push(`Email '${forwarder.email}' is already registered to another agency`);
      }
    }

    if (forwarder.taxId?.trim()) {
      const existing = await forwarderRepository.find(f => 
        f.taxId!.toLowerCase() === forwarder.taxId!.trim().toLowerCase() && 
        f.entityStatus !== 'DELETED' &&
        (!isUpdate || f.id !== forwarder.id)
      );
      if (existing.length > 0) {
        errors.push(`Tax ID '${forwarder.taxId}' is already registered to another agency`);
      }
    }

    // Rating check
    if (forwarder.rating !== undefined && (forwarder.rating < 1.0 || forwarder.rating > 5.0)) {
      errors.push('Performance Rating must be between 1.0 and 5.0');
    }

    if (errors.length > 0) {
      throw new Error(errors.join(' | '));
    }
  }

  /**
   * Add a timeline event to a forwarder
   */
  logEvent(
    forwarder: Forwarder, 
    type: ForwarderTimelineEvent['type'], 
    title: string, 
    description: string, 
    userId: string = 'USR-001'
  ): void {
    if (!forwarder.timeline) {
      forwarder.timeline = [];
    }
    
    const event: ForwarderTimelineEvent = {
      id: `EV-${Math.random().toString(36).substr(2, 9)}`,
      date: new Date().toISOString(),
      type,
      title,
      description,
      userId
    };

    forwarder.timeline.unshift(event);
  }

  /**
   * Clones a forwarder node.
   */
  async duplicate(id: string): Promise<Forwarder> {
    const original = await forwarderRepository.getById(id);
    if (!original) throw new Error('Forwarder matrix node not found');

    const duplicatedForwarder: Partial<Forwarder> = {
      ...original,
      id: undefined, // Generated by repo
      name: `${original.name} (Copy)`,
      taxId: original.taxId ? `${original.taxId}-COPY` : undefined,
      email: `copy.${original.email}`,
      timeline: [
        {
          id: `EV-${Math.random().toString(36).substr(2, 9)}`,
          date: new Date().toISOString(),
          type: 'CREATED',
          title: 'Agency Profile Duplicated',
          description: `Duplicated from original agency ID: ${original.id}.`,
          userId: 'USR-001'
        }
      ],
      entityStatus: 'ACTIVE'
    };

    return forwarderRepository.create(duplicatedForwarder);
  }
}

export const forwarderService = new ForwarderService();
