import { Product, ProductTimelineEvent } from '@/types';
import { productRepository } from '@/repositories/repository';

export class ProductService {
  /**
   * Validate a product instance for business rule compliance.
   * Throws an error with details if validation fails.
   */
  async validate(product: Partial<Product>, isUpdate: boolean = false): Promise<void> {
    const errors: string[] = [];

    // Required fields check
    if (!product.sku?.trim()) errors.push('SKU identifier is required');
    if (!product.name?.trim()) errors.push('Product name is required');
    if (!product.category?.trim()) errors.push('Category classification is required');
    if (!product.brand?.trim()) errors.push('Brand identifier is required');
    if (!product.countryOfOrigin?.trim()) errors.push('Country of origin is required');
    if (!product.hsnCode?.trim()) errors.push('HS Code is required');

    // Duplicate SKU check
    if (product.sku?.trim()) {
      const existing = await productRepository.find(p => 
        p.sku.toLowerCase() === product.sku!.trim().toLowerCase() && 
        p.entityStatus !== 'DELETED' &&
        (!isUpdate || p.id !== product.id)
      );
      if (existing.length > 0) {
        errors.push(`SKU '${product.sku}' is already registered in the matrix`);
      }
    }

    // Pricing checks
    if (product.purchasePrice !== undefined && product.purchasePrice < 0) {
      errors.push('Purchase Price cannot be negative');
    }
    if (product.sellingPrice !== undefined && product.sellingPrice < 0) {
      errors.push('Selling Price cannot be negative');
    }
    if (product.purchasePrice !== undefined && product.sellingPrice !== undefined && product.sellingPrice < product.purchasePrice) {
      errors.push('Selling Price must be equal to or greater than Purchase Price');
    }

    // Weight checks
    if (product.grossWeight !== undefined && product.grossWeight <= 0) {
      errors.push('Gross weight must be greater than zero');
    }
    if (product.netWeight !== undefined && product.netWeight <= 0) {
      errors.push('Net weight must be greater than zero');
    }
    if (product.grossWeight !== undefined && product.netWeight !== undefined && product.grossWeight < product.netWeight) {
      errors.push('Gross weight must be greater than or equal to Net weight');
    }

    // CBM check
    if (product.cbm !== undefined && product.cbm <= 0) {
      errors.push('CBM (volume) must be greater than zero');
    }

    // HSN Code validation: must be strictly numeric (between 6 and 10 digits after stripping punctuation)
    if (product.hsnCode?.trim()) {
      const strippedHSN = product.hsnCode.replace(/[\s.-]/g, '');
      const isNumeric = /^\d+$/.test(strippedHSN);
      if (!isNumeric || strippedHSN.length < 6 || strippedHSN.length > 10) {
        errors.push('HS Code must be a numeric sequence of 6 to 10 digits');
      }
    }

    if (errors.length > 0) {
      throw new Error(errors.join(' | '));
    }
  }

  /**
   * Add a timeline event to a product
   */
  logEvent(
    product: Product, 
    type: ProductTimelineEvent['type'], 
    title: string, 
    description: string, 
    userId: string = 'USR-001'
  ): void {
    if (!product.timeline) {
      product.timeline = [];
    }
    
    const event: ProductTimelineEvent = {
      id: `EV-${Math.random().toString(36).substr(2, 9)}`,
      date: new Date().toISOString(),
      type,
      title,
      description,
      userId
    };

    product.timeline.unshift(event);
  }

  /**
   * Clones a product, generating a new SKU and ID.
   */
  async duplicate(id: string): Promise<Product> {
    const original = await productRepository.getById(id);
    if (!original) throw new Error('Product matrix node not found');

    const copySku = `${original.sku}_COPY`;
    
    // Check if the duplicated SKU already exists, if so append unique tag
    let uniqueSku = copySku;
    let counter = 1;
    while ((await productRepository.find(p => p.sku === uniqueSku && p.entityStatus !== 'DELETED')).length > 0) {
      uniqueSku = `${copySku}_${counter}`;
      counter++;
    }

    const duplicatedProduct: Partial<Product> = {
      ...original,
      id: undefined, // Will be generated by repository.create
      sku: uniqueSku,
      name: `${original.name} (Copy)`,
      timeline: [
        {
          id: `EV-${Math.random().toString(36).substr(2, 9)}`,
          date: new Date().toISOString(),
          type: 'CREATED',
          title: 'Product Duplicated',
          description: `Duplicated from original product SKU: ${original.sku}.`,
          userId: 'USR-001'
        }
      ],
      purchaseHistory: [],
      sellingHistory: [],
      pricingHistory: [
        { date: new Date().toISOString(), price: original.sellingPrice, currency: original.currency }
      ],
      entityStatus: 'ACTIVE'
    };

    return productRepository.create(duplicatedProduct);
  }
}

export const productService = new ProductService();
