import { Quotation, QuotationTimelineEvent } from '@/types';
import { quotationRepository } from '@/repositories/repository';

export class QuotationService {
  /**
   * Validate a quotation for business rules.
   */
  async validate(quotation: Partial<Quotation>, isUpdate: boolean = false): Promise<void> {
    const errors: string[] = [];

    // Required fields check
    if (!quotation.customerId?.trim()) errors.push('Customer reference is required');
    if (!quotation.incoterm?.trim()) errors.push('Incoterm rule selection is required');
    if (!quotation.containerType?.trim()) errors.push('Container configuration type is required');
    if (!quotation.paymentTerms?.trim()) errors.push('Payment invoicing terms are required');
    if (!quotation.originPortId?.trim()) errors.push('Origin port of dispatch is required');
    if (!quotation.destinationPortId?.trim()) errors.push('Destination port of discharge is required');

    // Date range verification
    if (quotation.validityDate) {
      const valDate = new Date(quotation.validityDate);
      if (valDate.getTime() <= Date.now()) {
        errors.push('Validity expiration date must be in the future');
      }
    }

    // Exchange Rate
    if (quotation.exchangeRate !== undefined && quotation.exchangeRate <= 0) {
      errors.push('Exchange rate parameter must be greater than zero');
    }

    // Itemized lines check
    if (!quotation.items || quotation.items.length === 0) {
      errors.push('Quotation must contain at least one commercial item row');
    } else {
      quotation.items.forEach((item, idx) => {
        if (!item.productId?.trim()) {
          errors.push(`Row ${idx + 1}: Commodity item is not selected`);
        }
        if (item.quantity <= 0) {
          errors.push(`Row ${idx + 1}: Quantity must be greater than zero`);
        }
        if (item.unitPrice <= 0) {
          errors.push(`Row ${idx + 1}: Unit price must be greater than zero`);
        }
      });
    }

    // Unique Ref and Version check
    if (quotation.quotationNo?.trim()) {
      const versionVal = quotation.version || 1;
      const existing = await quotationRepository.find(q => 
        q.quotationNo.toLowerCase() === quotation.quotationNo!.trim().toLowerCase() &&
        q.version === versionVal &&
        q.entityStatus !== 'DELETED' &&
        (!isUpdate || q.id !== quotation.id)
      );
      if (existing.length > 0) {
        errors.push(`Quotation Reference '${quotation.quotationNo}' version ${versionVal} already exists`);
      }
    }

    if (errors.length > 0) {
      throw new Error(errors.join(' | '));
    }
  }

  /**
   * Add a timeline event to a quotation
   */
  logEvent(
    quotation: Quotation, 
    type: QuotationTimelineEvent['type'], 
    title: string, 
    description: string, 
    userId: string = 'USR-001'
  ): void {
    if (!quotation.timeline) {
      quotation.timeline = [];
    }
    
    const event: QuotationTimelineEvent = {
      id: `EV-${Math.random().toString(36).substr(2, 9)}`,
      date: new Date().toISOString(),
      type,
      title,
      description,
      userId
    };

    quotation.timeline.unshift(event);
  }

  /**
   * Revise a quotation, incrementing the version and creating a new draft while archiving the original.
   */
  async revise(id: string): Promise<Quotation> {
    const original = await quotationRepository.getById(id);
    if (!original) throw new Error('Quotation to revise not found');

    // Update original status to REVISED
    original.status = 'REVISED';
    this.logEvent(original, 'REVISED', `Revision ${original.version}.0 Closed`, `Closed and transitioned status to REVISED in favor of v${original.version + 1}.0.`);
    await quotationRepository.update(id, original);

    // Create revised copy
    const nextVersion = original.version + 1;
    const now = new Date().toISOString();
    
    const revisedPayload: Partial<Quotation> = {
      ...original,
      id: undefined, // Generated by repository
      version: nextVersion,
      status: 'DRAFT',
      date: now,
      validityDate: new Date(Date.now() + 30 * 86400000).toISOString(),
      timeline: [
        {
          id: `EV-${Math.random().toString(36).substr(2, 9)}`,
          date: now,
          type: 'CREATED',
          title: `Proposal Revised to v${nextVersion}.0`,
          description: `Revised from original quotation ID: ${original.id} (v${original.version}.0).`,
          userId: 'USR-001'
        }
      ],
      entityStatus: 'ACTIVE',
      createdAt: now,
      updatedAt: now
    };

    return quotationRepository.create(revisedPayload);
  }

  /**
   * Duplicates a quotation back to version 1.
   */
  async duplicate(id: string): Promise<Quotation> {
    const original = await quotationRepository.getById(id);
    if (!original) throw new Error('Quotation to duplicate not found');

    const now = new Date().toISOString();
    const qNo = `QT-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;

    const duplicatedPayload: Partial<Quotation> = {
      ...original,
      id: undefined,
      quotationNo: qNo,
      version: 1,
      status: 'DRAFT',
      date: now,
      validityDate: new Date(Date.now() + 30 * 86400000).toISOString(),
      timeline: [
        {
          id: `EV-${Math.random().toString(36).substr(2, 9)}`,
          date: now,
          type: 'CREATED',
          title: 'Proposal Duplicated',
          description: `Duplicated from original quotation ID: ${original.id}. Created under Ref No: ${qNo}.`,
          userId: 'USR-001'
        }
      ],
      entityStatus: 'ACTIVE',
      createdAt: now,
      updatedAt: now
    };

    return quotationRepository.create(duplicatedPayload);
  }
}

export const quotationService = new QuotationService();
