import { Supplier, SupplierTimelineEvent } from '@/types';
import { supplierRepository } from '@/repositories/repository';

export class SupplierService {
  /**
   * Validate a supplier instance for business rules.
   */
  async validate(supplier: Partial<Supplier>, isUpdate: boolean = false): Promise<void> {
    const errors: string[] = [];

    // Required fields check
    if (!supplier.name?.trim()) errors.push('Supplier identity name is required');
    if (!supplier.email?.trim()) errors.push('Contact email is required');
    if (!supplier.country?.trim()) errors.push('Country of origin/dispatch is required');
    if (!supplier.paymentTerms?.trim()) errors.push('Payment terms are required');

    // Email validation
    if (supplier.email?.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(supplier.email.trim())) {
        errors.push('Contact email format is invalid');
      }
    }

    // Website validation
    if (supplier.website?.trim()) {
      const webRegex = /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([\/\w .-]*)*\/?$/;
      if (!webRegex.test(supplier.website.trim())) {
        errors.push('Website URL format is invalid');
      }
    }

    // Unique Email and Tax ID check
    if (supplier.email?.trim()) {
      const existing = await supplierRepository.find(s => 
        s.email.toLowerCase() === supplier.email!.trim().toLowerCase() && 
        s.entityStatus !== 'DELETED' &&
        (!isUpdate || s.id !== supplier.id)
      );
      if (existing.length > 0) {
        errors.push(`Email '${supplier.email}' is already registered to another vendor`);
      }
    }

    if (supplier.taxId?.trim()) {
      const existing = await supplierRepository.find(s => 
        s.taxId!.toLowerCase() === supplier.taxId!.trim().toLowerCase() && 
        s.entityStatus !== 'DELETED' &&
        (!isUpdate || s.id !== supplier.id)
      );
      if (existing.length > 0) {
        errors.push(`Tax ID '${supplier.taxId}' is already registered to another vendor`);
      }
    }

    // Performance ratings range
    if (supplier.performanceRating !== undefined && (supplier.performanceRating < 1.0 || supplier.performanceRating > 5.0)) {
      errors.push('Performance Rating must be between 1.0 and 5.0');
    }

    // Lead time range
    if (supplier.averageLeadTime !== undefined && supplier.averageLeadTime <= 0) {
      errors.push('Average Lead Time must be greater than zero');
    }

    if (errors.length > 0) {
      throw new Error(errors.join(' | '));
    }
  }

  /**
   * Add a timeline event to a supplier
   */
  logEvent(
    supplier: Supplier, 
    type: SupplierTimelineEvent['type'], 
    title: string, 
    description: string, 
    userId: string = 'USR-001'
  ): void {
    if (!supplier.timeline) {
      supplier.timeline = [];
    }
    
    const event: SupplierTimelineEvent = {
      id: `EV-${Math.random().toString(36).substr(2, 9)}`,
      date: new Date().toISOString(),
      type,
      title,
      description,
      userId
    };

    supplier.timeline.unshift(event);
  }

  /**
   * Clones a supplier node.
   */
  async duplicate(id: string): Promise<Supplier> {
    const original = await supplierRepository.getById(id);
    if (!original) throw new Error('Supplier matrix node not found');

    const duplicatedSupplier: Partial<Supplier> = {
      ...original,
      id: undefined, // Generated by repo
      name: `${original.name} (Copy)`,
      taxId: original.taxId ? `${original.taxId}-COPY` : undefined,
      email: `copy.${original.email}`,
      timeline: [
        {
          id: `EV-${Math.random().toString(36).substr(2, 9)}`,
          date: new Date().toISOString(),
          type: 'CREATED',
          title: 'Vendor Profile Duplicated',
          description: `Duplicated from original vendor ID: ${original.id}.`,
          userId: 'USR-001'
        }
      ],
      entityStatus: 'ACTIVE'
    };

    return supplierRepository.create(duplicatedSupplier);
  }
}

export const supplierService = new SupplierService();
